export let sampleInstruction = {
	vegetarian: false,
	vegan: false,
	glutenFree: false,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	lowFodmap: false,
	weightWatcherSmartPoints: 13,
	gaps: "no",
	preparationMinutes: null,
	cookingMinutes: null,
	aggregateLikes: 2,
	healthScore: 10,
	creditsText: "foodista.com",
	sourceName: "foodista.com",
	pricePerServing: 208.81,
	extendedIngredients: [
		{
			id: 11215,
			aisle: "Produce",
			image: "garlic.png",
			consistency: "SOLID",
			name: "garlic",
			nameClean: "garlic",
			original: "1 large clove garlic, finely minced",
			originalName: "garlic, finely minced",
			amount: 1,
			unit: "large clove",
			meta: ["finely minced"],
			measures: {
				us: {
					amount: 1,
					unitShort: "large clove",
					unitLong: "large clove",
				},
				metric: {
					amount: 1,
					unitShort: "large clove",
					unitLong: "large clove",
				},
			},
		},
		{
			id: 1011033,
			aisle: "Cheese",
			image: "parmesan.jpg",
			consistency: "SOLID",
			name: "grana padano cheese",
			nameClean: "grana padano",
			original: "1/2 cup grated Parmesan or Grana Padano cheese",
			originalName: "grated Parmesan or Grana Padano cheese",
			amount: 0.5,
			unit: "cup",
			meta: ["grated"],
			measures: {
				us: {
					amount: 0.5,
					unitShort: "cups",
					unitLong: "cups",
				},
				metric: {
					amount: 50,
					unitShort: "g",
					unitLong: "grams",
				},
			},
		},
		{
			id: 1026,
			aisle: "Cheese",
			image: "mozzarella.png",
			consistency: "SOLID",
			name: "coarsely mozzarella",
			nameClean: "mozzarella",
			original: "1/2 cup coarsely grated mozzarella",
			originalName: "coarsely grated mozzarella",
			amount: 0.5,
			unit: "cup",
			meta: ["grated"],
			measures: {
				us: {
					amount: 0.5,
					unitShort: "cups",
					unitLong: "cups",
				},
				metric: {
					amount: 56,
					unitShort: "g",
					unitLong: "grams",
				},
			},
		},
		{
			id: 4053,
			aisle: "Oil, Vinegar, Salad Dressing",
			image: "olive-oil.jpg",
			consistency: "LIQUID",
			name: "olive oil",
			nameClean: "olive oil",
			original: "1 tablespoon olive oil",
			originalName: "olive oil",
			amount: 1,
			unit: "tablespoon",
			meta: [],
			measures: {
				us: {
					amount: 1,
					unitShort: "Tbsp",
					unitLong: "Tbsp",
				},
				metric: {
					amount: 1,
					unitShort: "Tbsp",
					unitLong: "Tbsp",
				},
			},
		},
		{
			id: 11282,
			aisle: "Produce",
			image: "brown-onion.png",
			consistency: "SOLID",
			name: "onion",
			nameClean: "onion",
			original: "1 small onion, finely chopped",
			originalName: "onion, finely chopped",
			amount: 1,
			unit: "small",
			meta: ["finely chopped"],
			measures: {
				us: {
					amount: 1,
					unitShort: "small",
					unitLong: "small",
				},
				metric: {
					amount: 1,
					unitShort: "small",
					unitLong: "small",
				},
			},
		},
		{
			id: 2027,
			aisle: "Spices and Seasonings",
			image: "oregano.jpg",
			consistency: "SOLID",
			name: "oregano",
			nameClean: "oregano",
			original: "1 teaspoon dried oregano, crumbled",
			originalName: "dried oregano, crumbled",
			amount: 1,
			unit: "teaspoon",
			meta: ["dried", "crumbled"],
			measures: {
				us: {
					amount: 1,
					unitShort: "tsp",
					unitLong: "teaspoon",
				},
				metric: {
					amount: 1,
					unitShort: "tsp",
					unitLong: "teaspoon",
				},
			},
		},
		{
			id: 1102047,
			aisle: "Spices and Seasonings",
			image: "salt-and-pepper.jpg",
			consistency: "SOLID",
			name: "salt and pepper",
			nameClean: "salt and pepper",
			original: "Salt and pepper",
			originalName: "Salt and pepper",
			amount: 3,
			unit: "servings",
			meta: [],
			measures: {
				us: {
					amount: 3,
					unitShort: "servings",
					unitLong: "servings",
				},
				metric: {
					amount: 3,
					unitShort: "servings",
					unitLong: "servings",
				},
			},
		},
		{
			id: 19335,
			aisle: "Baking",
			image: "sugar-in-bowl.png",
			consistency: "SOLID",
			name: "sugar",
			nameClean: "sugar",
			original: "1 teaspoon sugar",
			originalName: "sugar",
			amount: 1,
			unit: "teaspoon",
			meta: [],
			measures: {
				us: {
					amount: 1,
					unitShort: "tsp",
					unitLong: "teaspoon",
				},
				metric: {
					amount: 1,
					unitShort: "tsp",
					unitLong: "teaspoon",
				},
			},
		},
		{
			id: 11529,
			aisle: "Produce",
			image: "tomato.png",
			consistency: "SOLID",
			name: "tomatoes",
			nameClean: "tomato",
			original: "400 grams chopped tomatoes",
			originalName: "chopped tomatoes",
			amount: 400,
			unit: "grams",
			meta: ["chopped"],
			measures: {
				us: {
					amount: 14.11,
					unitShort: "oz",
					unitLong: "ounces",
				},
				metric: {
					amount: 400,
					unitShort: "g",
					unitLong: "grams",
				},
			},
		},
		{
			id: 93727,
			aisle: "Pasta and Rice",
			image: "tortellini-isolated.jpg",
			consistency: "SOLID",
			name: "tortellini",
			nameClean: "cooked cheese tortellini",
			original: "250 grams fresh tortellini (with cheese or spinach)",
			originalName: "fresh tortellini (with cheese or spinach)",
			amount: 250,
			unit: "grams",
			meta: ["fresh", "with cheese or spinach)"],
			measures: {
				us: {
					amount: 8.818,
					unitShort: "oz",
					unitLong: "ounces",
				},
				metric: {
					amount: 250,
					unitShort: "g",
					unitLong: "grams",
				},
			},
		},
	],
	id: 633858,
	title: "Baked Tortellini In Red Sauce",
	readyInMinutes: 45,
	servings: 3,
	sourceUrl: "http://www.foodista.com/recipe/VFPZW5TP/baked-tortellini-in-red-sauce",
	image: "https://img.spoonacular.com/recipes/633858-556x370.jpg",
	imageType: "jpg",
	summary:
		'The recipe Baked Tortellini In Red Sauce can be made \u003Cb\u003Ein around 45 minutes\u003C/b\u003E. This recipe makes 3 servings with \u003Cb\u003E463 calories\u003C/b\u003E, \u003Cb\u003E24g of protein\u003C/b\u003E, and \u003Cb\u003E21g of fat\u003C/b\u003E each. For \u003Cb\u003E$2.09 per serving\u003C/b\u003E, this recipe \u003Cb\u003Ecovers 13%\u003C/b\u003E of your daily requirements of vitamins and minerals. This recipe is liked by 2 foodies and cooks. It is brought to you by Foodista. It works well as a main course. Head to the store and pick up garlic, sugar, salt and pepper, and a few other things to make it today. All things considered, we decided this recipe \u003Cb\u003Edeserves a spoonacular score of 50%\u003C/b\u003E. This score is solid. \u003Ca href="https://spoonacular.com/recipes/tortellini-with-red-wine-sauce-516170"\u003ETortellini with Red Wine Sauce\u003C/a\u003E, \u003Ca href="https://spoonacular.com/recipes/baked-red-snapper-in-dill-sauce-88487"\u003EBaked Red Snapper in Dill Sauce\u003C/a\u003E, and \u003Ca href="https://spoonacular.com/recipes/baked-rutabaga-with-red-eye-tomato-sauce-707045"\u003EBaked Rutabaga with "Red-Eye" Tomato Sauce\u003C/a\u003E are very similar to this recipe.',
	cuisines: [],
	dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
	diets: [],
	occasions: [],
	instructions:
		"\u003Col\u003E\u003Cli\u003ESaut onion and garlic in olive oil for 5 minutes.\u003C/li\u003E\u003Cli\u003ESeason with salt, pepper and oregano.\u003C/li\u003E\u003Cli\u003EAdd chopped tomatoes and their juice. Season with salt, pepper and oregano.\u003C/li\u003E\u003Cli\u003EMix and bring to a boil. Sprinkle with sugar and reduce heat. Cook over low heat for 20 minutes. Adjust seasoning.\u003C/li\u003E\u003Cli\u003EMeanwhile, plunge the pasta in salted boiling water just long enough that they float to the surface. Drain the pasta and return to pot.\u003C/li\u003E\u003Cli\u003EToss pasta with tomato sauce. Transfer to the lightly oiled baking dish and sprinkle with grated cheese.\u003C/li\u003E\u003Cli\u003EBake at 240C for 20-25 minutes, until the surface of the dish is well baked. Remove pan from oven and let stand 5 minutes before serving.\u003C/li\u003E\u003Cli\u003EServe with a green salad.\u003C/li\u003E\u003C/ol\u003E",
	analyzedInstructions: [
		{
			name: "",
			steps: [
				{
					number: 1,
					step: "Saut onion and garlic in olive oil for 5 minutes.Season with salt, pepper and oregano.",
					ingredients: [
						{
							id: 4053,
							name: "olive oil",
							localizedName: "olive oil",
							image: "https://spoonacular.com/cdn/ingredients_100x100/olive-oil.jpg",
						},
						{
							id: 2027,
							name: "oregano",
							localizedName: "oregano",
							image: "https://spoonacular.com/cdn/ingredients_100x100/oregano.jpg",
						},
						{
							id: 11215,
							name: "garlic",
							localizedName: "garlic",
							image: "https://spoonacular.com/cdn/ingredients_100x100/garlic.png",
						},
						{
							id: 1002030,
							name: "pepper",
							localizedName: "pepper",
							image: "https://spoonacular.com/cdn/ingredients_100x100/pepper.jpg",
						},
						{
							id: 11282,
							name: "onion",
							localizedName: "onion",
							image: "https://spoonacular.com/cdn/ingredients_100x100/brown-onion.png",
						},
						{
							id: 2047,
							name: "salt",
							localizedName: "salt",
							image: "https://spoonacular.com/cdn/ingredients_100x100/salt.jpg",
						},
					],
					equipment: [],
					length: {
						number: 5,
						unit: "minutes",
					},
				},
				{
					number: 2,
					step: "Add chopped tomatoes and their juice. Season with salt, pepper and oregano.",
					ingredients: [
						{
							id: 11529,
							name: "tomato",
							localizedName: "tomato",
							image: "https://spoonacular.com/cdn/ingredients_100x100/tomato.png",
						},
						{
							id: 2027,
							name: "oregano",
							localizedName: "oregano",
							image: "https://spoonacular.com/cdn/ingredients_100x100/oregano.jpg",
						},
						{
							id: 1002030,
							name: "pepper",
							localizedName: "pepper",
							image: "https://spoonacular.com/cdn/ingredients_100x100/pepper.jpg",
						},
						{
							id: 1019016,
							name: "juice",
							localizedName: "juice",
							image: "https://spoonacular.com/cdn/ingredients_100x100/apple-juice.jpg",
						},
						{
							id: 2047,
							name: "salt",
							localizedName: "salt",
							image: "https://spoonacular.com/cdn/ingredients_100x100/salt.jpg",
						},
					],
					equipment: [],
				},
				{
					number: 3,
					step: "Mix and bring to a boil.",
					ingredients: [],
					equipment: [],
				},
				{
					number: 4,
					step: "Sprinkle with sugar and reduce heat. Cook over low heat for 20 minutes. Adjust seasoning.Meanwhile, plunge the pasta in salted boiling water just long enough that they float to the surface.",
					ingredients: [
						{
							id: 1042027,
							name: "seasoning",
							localizedName: "seasoning",
							image: "https://spoonacular.com/cdn/ingredients_100x100/seasoning.png",
						},
						{
							id: 20420,
							name: "pasta",
							localizedName: "pasta",
							image: "https://spoonacular.com/cdn/ingredients_100x100/fusilli.jpg",
						},
						{
							id: 19335,
							name: "sugar",
							localizedName: "sugar",
							image: "https://spoonacular.com/cdn/ingredients_100x100/sugar-in-bowl.png",
						},
						{
							id: 14412,
							name: "water",
							localizedName: "water",
							image: "https://spoonacular.com/cdn/ingredients_100x100/water.png",
						},
					],
					equipment: [],
					length: {
						number: 20,
						unit: "minutes",
					},
				},
				{
					number: 5,
					step: "Drain the pasta and return to pot.Toss pasta with tomato sauce.",
					ingredients: [
						{
							id: 11549,
							name: "tomato sauce",
							localizedName: "tomato sauce",
							image:
								"https://spoonacular.com/cdn/ingredients_100x100/tomato-sauce-or-pasta-sauce.jpg",
						},
						{
							id: 20420,
							name: "pasta",
							localizedName: "pasta",
							image: "https://spoonacular.com/cdn/ingredients_100x100/fusilli.jpg",
						},
					],
					equipment: [
						{
							id: 404752,
							name: "pot",
							localizedName: "pot",
							image: "https://spoonacular.com/cdn/equipment_100x100/stock-pot.jpg",
						},
					],
				},
				{
					number: 6,
					step: "Transfer to the lightly oiled baking dish and sprinkle with grated cheese.",
					ingredients: [
						{
							id: 1041009,
							name: "cheese",
							localizedName: "cheese",
							image: "https://spoonacular.com/cdn/ingredients_100x100/cheddar-cheese.png",
						},
					],
					equipment: [
						{
							id: 404646,
							name: "baking pan",
							localizedName: "baking pan",
							image: "https://spoonacular.com/cdn/equipment_100x100/roasting-pan.jpg",
						},
					],
				},
				{
					number: 7,
					step: "Bake at 240C for 20-25 minutes, until the surface of the dish is well baked.",
					ingredients: [],
					equipment: [
						{
							id: 404784,
							name: "oven",
							localizedName: "oven",
							image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
							temperature: {
								number: 240,
								unit: "Celsius",
							},
						},
					],
					length: {
						number: 25,
						unit: "minutes",
					},
				},
				{
					number: 8,
					step: "Remove pan from oven and let stand 5 minutes before serving.",
					ingredients: [],
					equipment: [
						{
							id: 404784,
							name: "oven",
							localizedName: "oven",
							image: "https://spoonacular.com/cdn/equipment_100x100/oven.jpg",
						},
						{
							id: 404645,
							name: "frying pan",
							localizedName: "frying pan",
							image: "https://spoonacular.com/cdn/equipment_100x100/pan.png",
						},
					],
					length: {
						number: 5,
						unit: "minutes",
					},
				},
				{
					number: 9,
					step: "Serve with a green salad.",
					ingredients: [],
					equipment: [],
				},
			],
		},
	],
	originalId: null,
	spoonacularScore: 54.2226333618164,
	spoonacularSourceUrl: "https://spoonacular.com/baked-tortellini-in-red-sauce-633858",
};
export let sampleData = {
	results: [
		{
			id: 633858,
			title: "Baked Tortellini In Red Sauce",
			image: "https://img.spoonacular.com/recipes/633858-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 632778,
			title: "Artisan Farfalle Pasta With Smoked Salmon and Cream Sauce",
			image: "https://img.spoonacular.com/recipes/632778-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 643642,
			title: "Macaroni Pasta with Fresh Tomatoes, Zucchini and Artichokes",
			image: "https://img.spoonacular.com/recipes/643642-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 642583,
			title: "Farfalle with Peas, Ham and Cream",
			image: "https://img.spoonacular.com/recipes/642583-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 645354,
			title: "Greek Shrimp Orzo",
			image: "https://img.spoonacular.com/recipes/645354-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 642722,
			title: "Fettuccine With Smashed Peas",
			image: "https://img.spoonacular.com/recipes/642722-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 606953,
			title: "Cajun Chicken Pasta",
			image: "https://img.spoonacular.com/recipes/606953-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 642582,
			title: "Farfalle With Broccoli, Carrots and Tomatoes",
			image: "https://img.spoonacular.com/recipes/642582-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 663813,
			title: "Tricolor Rotini pasta Salad",
			image: "https://img.spoonacular.com/recipes/663813-312x231.jpg",
			imageType: "jpg",
		},
		{
			id: 452116,
			title: "Rustic Red Wine Spaghetti",
			image: "https://img.spoonacular.com/recipes/452116-312x231.jpg",
			imageType: "jpg",
		},
	],
	offset: 0,
	number: 10,
	totalResults: 250,
};